/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemaproject;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author My PC
 */
public class Addemployee extends javax.swing.JFrame {

    /**
     * Creates new form Createaccount
     */
    public static Connection getConnection() {
        Connection con = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "root", "");
            System.out.print("Connected To Database");

        } catch (Exception e) {
            System.out.println("Database connection error:   " + e.getMessage());
        }

        return con;
    }

    public void AddUser() {

        String gender = "";
        if (jRadioButton2.isSelected()) {
            gender = jRadioButton2.getText();
        }
        if (jRadioButton1.isSelected()) {
            gender = jRadioButton1.getText();
        }
        String Role=(String)jComboBox2.getSelectedItem();
        String name = firstnametextbox.getText();
        String username = lastnametextbox.getText();
        String password = String.valueOf(passwordtextbox.getText());
        String phone = phonetextbox.getText();
        String email = emailtextbox.getText();
        String salary = salarytextbox.getText();
        PreparedStatement ps;
        String query = "INSERT INTO login(name, username, password, gender, phone, email,salary,Usertype) VALUES (?,?,?,?,?,?,?,?)";
//                   
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, name);
            ps.setString(2, username);
            ps.setString(3, password);
            ps.setString(4, gender);
            ps.setString(5, phone);
            ps.setString(6, email);
            ps.setString(7, salary);
            ps.setString(8, Role);
            if (ps.executeUpdate() > 0) {
               JOptionPane option = new JOptionPane();
                option.showMessageDialog(null, "Employee Registerd");
               ManageAccount L = new ManageAccount ();
                L.setVisible(true);
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }

    public Addemployee() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        addemployee = new javax.swing.JLabel();
        fillnamelabel = new javax.swing.JLabel();
        lastnametextbox = new javax.swing.JTextField();
        lastnamelabel = new javax.swing.JLabel();
        firstnametextbox = new javax.swing.JTextField();
        passwordlabel = new javax.swing.JLabel();
        passwordtextbox = new javax.swing.JTextField();
        phoneylabel = new javax.swing.JLabel();
        phonetextbox = new javax.swing.JTextField();
        confirmbutton = new javax.swing.JButton();
        emaillabel = new javax.swing.JLabel();
        emailtextbox = new javax.swing.JTextField();
        salarylabel = new javax.swing.JLabel();
        salarytextbox = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addemployee.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        addemployee.setForeground(new java.awt.Color(255, 255, 255));
        addemployee.setText("Add Employee");
        jPanel1.add(addemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 33, -1, -1));

        fillnamelabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fillnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        fillnamelabel.setText("Full Name");
        jPanel1.add(fillnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        lastnametextbox.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(lastnametextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 297, -1));

        lastnamelabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lastnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        lastnamelabel.setText("User Name");
        jPanel1.add(lastnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        firstnametextbox.setBackground(new java.awt.Color(204, 204, 204));
        firstnametextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnametextboxActionPerformed(evt);
            }
        });
        jPanel1.add(firstnametextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 297, -1));

        passwordlabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordlabel.setText("Password");
        jPanel1.add(passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        passwordtextbox.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(passwordtextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 297, -1));

        phoneylabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        phoneylabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneylabel.setText("Phone Number");
        jPanel1.add(phoneylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        phonetextbox.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(phonetextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 297, -1));

        confirmbutton.setBackground(new java.awt.Color(204, 204, 204));
        confirmbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        confirmbutton.setText("Confirm");
        confirmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        emaillabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emaillabel.setForeground(new java.awt.Color(255, 255, 255));
        emaillabel.setText("Email");
        jPanel1.add(emaillabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        emailtextbox.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(emailtextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 297, -1));

        salarylabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        salarylabel.setForeground(new java.awt.Color(255, 255, 255));
        salarylabel.setText("Salary");
        jPanel1.add(salarylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        salarytextbox.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(salarytextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 297, -1));

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 60, -1));

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 60, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "employee", "Administrator" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void confirmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbuttonActionPerformed

        // TODO add your handling code here:
        AddUser();
    }//GEN-LAST:event_confirmbuttonActionPerformed

    private void firstnametextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnametextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnametextboxActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addemployee;
    private javax.swing.JButton confirmbutton;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField emailtextbox;
    private javax.swing.JLabel fillnamelabel;
    private javax.swing.JTextField firstnametextbox;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JTextField lastnametextbox;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JTextField passwordtextbox;
    private javax.swing.JTextField phonetextbox;
    private javax.swing.JLabel phoneylabel;
    private javax.swing.JLabel salarylabel;
    private javax.swing.JTextField salarytextbox;
    // End of variables declaration//GEN-END:variables

//    private Addemployee() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
}
