/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemaproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author My PC
 */
public class Createaccount extends javax.swing.JFrame {

    /**
     * Creates new form Createaccount
     */
        public static Connection getConnection() {
        Connection con = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", "root", "");
            System.out.print("Connected To Database");

        } catch (Exception e) {
            System.out.println("Database connection error:   " + e.getMessage());
        }

        return con;
    }

    public void AddUser() {

        String name = firstnametextbox.getText();
        String username = lastnametextbox.getText();
        String password = String.valueOf(jPasswordField1.getText());
        String phone = phonetextbox.getText();
        PreparedStatement ps;
        String query = "INSERT INTO users(name, username, password,phone) VALUES (?,?,?,?)";
//                   
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, name);
            ps.setString(2, username);
            ps.setString(3, password);
            ps.setString(4, phone);
            if (ps.executeUpdate() > 0) {
              this.dispose();
              Login L =new Login();
                  L.show();
                   this.setVisible(false);
                System.out.print("Added");
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }
    public Createaccount() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fillnamelabel = new javax.swing.JLabel();
        lastnametextbox = new javax.swing.JTextField();
        lastnamelabel1 = new javax.swing.JLabel();
        firstnametextbox = new javax.swing.JTextField();
        passwordlabel = new javax.swing.JLabel();
        phoneylabel = new javax.swing.JLabel();
        phonetextbox = new javax.swing.JTextField();
        signupbutton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 130, -1));

        fillnamelabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fillnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        fillnamelabel.setText("Full Name");
        jPanel1.add(fillnamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lastnametextbox.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(lastnametextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 297, -1));

        lastnamelabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lastnamelabel1.setForeground(new java.awt.Color(255, 255, 255));
        lastnamelabel1.setText("User Name");
        jPanel1.add(lastnamelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        firstnametextbox.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(firstnametextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 297, -1));

        passwordlabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordlabel.setText("Password");
        jPanel1.add(passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        phoneylabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        phoneylabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneylabel.setText("Phone Number");
        jPanel1.add(phoneylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        phonetextbox.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(phonetextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 297, -1));

        signupbutton.setBackground(new java.awt.Color(153, 0, 0));
        signupbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        signupbutton.setText("Sign Up");
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(signupbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 300, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
        // TODO add your handling code here:
        AddUser();
    }//GEN-LAST:event_signupbuttonActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Createaccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fillnamelabel;
    private javax.swing.JTextField firstnametextbox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lastnamelabel1;
    private javax.swing.JTextField lastnametextbox;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JTextField phonetextbox;
    private javax.swing.JLabel phoneylabel;
    private javax.swing.JButton signupbutton;
    // End of variables declaration//GEN-END:variables
}
