/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemaproject;

/**
 *
 * @author HP
 */
public class Seats extends javax.swing.JFrame {

    /**
     * Creates new form Seats
     */
    public Seats() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        C5 = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setTitle("Choose your seat");
        setPreferredSize(new java.awt.Dimension(600, 650));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("seat");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, 40));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 50, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Choose your seat:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 200, 50));

        jPanel2.setBackground(new java.awt.Color(203, 197, 197));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(189, 189, 189), null, null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("S   C   R   E   E   N  ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 250, 60));

        C5.setBackground(new java.awt.Color(0, 0, 0));
        C5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        C5.setForeground(new java.awt.Color(255, 255, 255));
        C5.setText("C5");
        C5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 40, 40));

        A1.setBackground(new java.awt.Color(0, 0, 0));
        A1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        A1.setForeground(new java.awt.Color(255, 255, 255));
        A1.setText("A1");
        A1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 40, 40));

        A2.setBackground(new java.awt.Color(0, 0, 0));
        A2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        A2.setForeground(new java.awt.Color(255, 255, 255));
        A2.setText("A2");
        A2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 40, 40));

        A3.setBackground(new java.awt.Color(0, 0, 0));
        A3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        A3.setForeground(new java.awt.Color(255, 255, 255));
        A3.setText("A3");
        A3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 40, 40));

        A4.setBackground(new java.awt.Color(0, 0, 0));
        A4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        A4.setForeground(new java.awt.Color(255, 255, 255));
        A4.setText("A4");
        A4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 40, 40));

        A5.setBackground(new java.awt.Color(0, 0, 0));
        A5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        A5.setForeground(new java.awt.Color(255, 255, 255));
        A5.setText("A5");
        A5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 40, 40));

        B4.setBackground(new java.awt.Color(0, 0, 0));
        B4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        B4.setForeground(new java.awt.Color(255, 255, 255));
        B4.setText("B4");
        B4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 40, 40));

        B2.setBackground(new java.awt.Color(0, 0, 0));
        B2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        B2.setForeground(new java.awt.Color(255, 255, 255));
        B2.setText("B2");
        B2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 40, 40));

        B3.setBackground(new java.awt.Color(0, 0, 0));
        B3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        B3.setForeground(new java.awt.Color(255, 255, 255));
        B3.setText("B3");
        B3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 40, 40));

        B1.setBackground(new java.awt.Color(0, 0, 0));
        B1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        B1.setForeground(new java.awt.Color(255, 255, 255));
        B1.setText("B1");
        B1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 40, 40));

        B5.setBackground(new java.awt.Color(0, 0, 0));
        B5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        B5.setForeground(new java.awt.Color(255, 255, 255));
        B5.setText("B5");
        B5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 40, 40));

        C1.setBackground(new java.awt.Color(0, 0, 0));
        C1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        C1.setForeground(new java.awt.Color(255, 255, 255));
        C1.setText("C1");
        C1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 40, 40));

        C2.setBackground(new java.awt.Color(0, 0, 0));
        C2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        C2.setForeground(new java.awt.Color(255, 255, 255));
        C2.setText("C2");
        C2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 40, 40));

        C3.setBackground(new java.awt.Color(0, 0, 0));
        C3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        C3.setForeground(new java.awt.Color(255, 255, 255));
        C3.setText("C3");
        C3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 40, 40));

        C4.setBackground(new java.awt.Color(0, 0, 0));
        C4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        C4.setForeground(new java.awt.Color(255, 255, 255));
        C4.setText("C4");
        C4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 40, 40));

        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 40, 40));

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 51), 2, true));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 40, 40));

        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 40, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Reserved ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Your seat ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Available  ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton1.setText("Back");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 120, 30));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton2.setText("Book");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 120, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("___________Standard 55SR__________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("___________Premium 65SR__________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backEssential.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 550, -1));

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C5jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C5jButton1ActionPerformed

    private void A1jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1jButton1ActionPerformed

    private void A2jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2jButton1ActionPerformed

    private void A3jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3jButton1ActionPerformed

    private void A4jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4jButton1ActionPerformed

    private void A5jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A5jButton1ActionPerformed

    private void B4jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4jButton1ActionPerformed

    private void B2jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2jButton1ActionPerformed

    private void B3jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3jButton1ActionPerformed

    private void B1jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1jButton1ActionPerformed

    private void B5jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5jButton1ActionPerformed

    private void C1jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1jButton1ActionPerformed

    private void C2jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C2jButton1ActionPerformed

    private void C3jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C3jButton1ActionPerformed

    private void C4jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C4jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
